# Generated by Django 4.0.4 on 2022-04-19 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_expenses', '0002_expense_user_income_user_relativity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_expense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='income',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_income', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relativity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_relativity', to=settings.AUTH_USER_MODEL),
        ),
    ]
