# Generated by Django 4.0.4 on 2022-04-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_expenses', '0003_alter_expense_color_alter_expense_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='color',
        ),
        migrations.RemoveField(
            model_name='income',
            name='color',
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('BYN', 'Белорусский рубль'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='BYN', max_length=3),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('BYN', 'Белорусский рубль'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='income',
            name='created',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_income', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relativity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relativity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_expense', to='app_expenses.category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_income', to='app_expenses.category'),
        ),
    ]
